.\" -*- nroff -*-
.\" Copyright 1998-2004 AbiSource, Inc.
.\" AbiWord and AbiSource are trademarks of
.\" AbiSource, Inc.
.\"
.\" AbiWord is free software; you can redistribute it
.\" and/or modify it under the terms of the GNU General
.\" Public License as published by the Free Software
.\" Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the
.\" implied warranty of MERCHANTABILITY or FITNESS
.\" FOR A PARTICULAR PURPOSE.  See the GNU General
.\" Public License for more details.
.\"
.TH AbiWord 1 "2004" "AbiWord 2.2"
.SH NAME
AbiWord - AbiWord Word Processor
.SH SYNOPSIS
/usr/bin/abiword [ options ] [ files ]
.SH DESCRIPTION
The AbiWord project began as a desire to create a stable, feature-savvy word processor unbound by a single platform or proprietary file formats. Today AbiWord compiles as a native application on a wide collection of computers and can handle an equally impressive number of file formats.
.SH OPTIONS
.B --geometry=GEOMETRY_STRING
.RS
Sets the initial frame geometry. X11-like geometry string.
.RE
.B --nosplash
.RS
Do not show the splash screen
.RE
.B --to=FORMAT or FILENAME
.RS
Target format of file or new target filename. For conversion AbiWord documents.
[abw, zabw, rtf, txt, utf8, html, latex, etc]
.RE
.B --verbose
.RS
Specify the amount required amount of detail of the message information.
.RE
.B --plugin=PLUGIN_NAME
.RS
Execute plugin instead of the main application
.RE
.B --print=FILE or |lpr
.RS
Print any documents passed on the command line to FILE or send the output to the specified print command
.RE
.B --show
.RS
Force the Graphical User Interface (GUI) to be shown, even if using the options
.B --to
or
.B --help
.RE
.B --version
.RS
Report the version of AbiWord.
.RE
.B --help
.RS
Displays a helpful message explaining AbiWord's usage
.RE
.RE
.SH BUGS
Some platforms do not yet support all features at the time of writing.
Submit bugs to the Bugzilla bug tracking system at the AbiSource.com website.  Your contributions are appreciated.
.B http://bugzilla.abisource.com
.SH SEE ALSO
.BR wvWare(1), 
.BR psiconv, 
.BR ispell(1)
.SH HISTORY
AbiWord was originally started by SourceGear.  AbiWord is currently an Open Source Project run by volunteers. 
